//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OddBasyBY.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OddAdbaseEntity : DbContext
    {
        public OddAdbaseEntity()
            : base("name=OddAdbaseEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Segment> Segment { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<IntelliSenseStreet> IntelliSenseStreet { get; set; }
        public virtual DbSet<Mackup> Mackup { get; set; }
        public virtual DbSet<SpecificationofRM> SpecificationofRM { get; set; }
    }
}
