
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sciencecom.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AdType
{

    public AdType()
    {

        this.Billboards = new HashSet<Billboard>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }



    public virtual ICollection<Billboard> Billboards { get; set; }

}

}
