
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sciencecom.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Billboard
{

    public Billboard()
    {

        this.Sides = new HashSet<Side>();

    }


    public int Id { get; set; }

    public string Street1 { get; set; }

    public string House1 { get; set; }

    public string Street2 { get; set; }

    public string FromStreet { get; set; }

    public string Comment { get; set; }

    public string ContractNumber { get; set; }

    public string PassportNumber { get; set; }

    public System.DateTime StartDate { get; set; }

    public System.DateTime EndDate { get; set; }

    public bool OnAgreement { get; set; }

    public double Latitude { get; set; }

    public double Longitude { get; set; }



    public virtual Owner Owner { get; set; }

    public virtual ICollection<Side> Sides { get; set; }

    public virtual AdType AdType { get; set; }

}

}
