

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sciencecom.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SciencecomEntities : DbContext
{
    public SciencecomEntities()
        : base("name=SciencecomEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<LightConstruction> LightConstructions { get; set; }

    public virtual DbSet<MetalConstruction> MetalConstructions { get; set; }

    public virtual DbSet<Owner> Owners { get; set; }

    public virtual DbSet<Street> Streets { get; set; }

    public virtual DbSet<IllegalConstruction> IllegalConstructions { get; set; }

    public virtual DbSet<Billboard> Billboards { get; set; }

    public virtual DbSet<AdType> AdTypes { get; set; }

    public virtual DbSet<Side> Sides { get; set; }

    public virtual DbSet<Surface> Surfaces { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

}

}

