
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sciencecom.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LightConstruction
{

    public int Id { get; set; }

    public int IdOwner { get; set; }

    public int Support { get; set; }

    public string Street1 { get; set; }

    public string Street2 { get; set; }

    public string FromStreet { get; set; }

    public System.DateTime StartDate { get; set; }

    public System.DateTime FinishDate { get; set; }

    public bool IsSocial { get; set; }

    public bool OnStatement { get; set; }

    public string Locality { get; set; }

    public int IdWhoAdded { get; set; }

    public string DateOfSocial { get; set; }

    public float Shirota { get; set; }

    public float Dolgota { get; set; }



    public virtual Owner Owner { get; set; }

    public virtual Owner OwnerWhoAdded { get; set; }

}

}
