//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sciencecom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public Owner()
        {
            this.LightConstructions = new HashSet<LightConstruction>();
            this.MetalConstructions = new HashSet<MetalConstruction>();
            this.LightConstructionsWhoAdded = new HashSet<LightConstruction>();
            this.MetalConstructionsWhoAdded = new HashSet<MetalConstruction>();
            this.Billboards1 = new HashSet<Billboards1>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
    
        public virtual ICollection<LightConstruction> LightConstructions { get; set; }
        public virtual ICollection<MetalConstruction> MetalConstructions { get; set; }
        public virtual ICollection<LightConstruction> LightConstructionsWhoAdded { get; set; }
        public virtual ICollection<MetalConstruction> MetalConstructionsWhoAdded { get; set; }
        public virtual ICollection<Billboards1> Billboards1 { get; set; }
    }
}
