//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sciencecom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationshipOfAdvertising
    {
        public System.Guid id { get; set; }
        public System.Guid idOfTopicForSocialAdvertising { get; set; }
        public System.Guid idOfSubtopicForSocialAdvertising { get; set; }
        public bool Visible { get; set; }
        public System.Guid id_Object { get; set; }
    
        public virtual SubtopicForSocialAdvertising SubtopicForSocialAdvertising { get; set; }
        public virtual Object Object { get; set; }
        public virtual TopicForSocialAdvertising TopicForSocialAdvertising { get; set; }
    }
}
