//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sciencecom.Models
{
    using System.Collections.Generic;

    public partial class TypeOfAdvertisingStructure
    {
        public TypeOfAdvertisingStructure()
        {
            this.AdvertisingStructures = new HashSet<AdvertisingStructure>();
            this.Increments = new HashSet<Increment>();
            this.ListUniqueNumbers = new HashSet<ListUniqueNumber>();
        }
    
        public System.Guid id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<AdvertisingStructure> AdvertisingStructures { get; set; }
        public virtual ICollection<Increment> Increments { get; set; }
        public virtual ICollection<ListUniqueNumber> ListUniqueNumbers { get; set; }
    }
}
